import {test, expect} from '@playwright/test'

test('Первый тест', async ({page}) => {
    await page.goto('https://jpetstore.aspectran.com/catalog/')
    await expect(page).toHaveURL('https://jpetstore.aspectran.com/catalog/')
    const searchField = page.locator('[id="Search"]')
    await expect(searchField).toBeVisible()
    await searchField.click()
    await searchField.type('Кошки')
    const searchButton = page.locator('[class="input-group-button"]').last()
    await expect(searchButton).toBeVisible()
    await expect(searchButton).toHaveText('Search')
})

test('Селекторы', async ({page}) => {
    await page.goto('https://jpetstore.aspectran.com/catalog/')
    const signIn = page.locator('text = Sign In')
    const logo = page.locator('#Logo')
    const grid = page.locator('.grid-container').nth(6)
    const masthead = page.locator('[id="masthead"]')
    const search = page.locator('.input-group-button', {hasText: "Search"})
    const placeholder = page.locator('#Search', {has: page.locator('[placeholder="Product Search"]')}) 
    const placeholder2 = page.locator('[id="Search"]>>[class="input-group-field"]')
    await expect(placeholder2).toHaveAttribute('placeholder', 'Product Search')
    await expect(signIn).toBeVisible()
    await expect(logo).toBeVisible()
    await expect(grid).toBeVisible()
    await expect(masthead).toBeVisible()
    await expect(search).toBeVisible()
    await expect(placeholder).toBeVisible()
})