import {test, expect} from '@playwright/test'

test('нажать на кнопку “Sign In”, проверить url -> url заканчивается на /account/signonForm ', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/')
    const signInButton = page.locator('[href="/account/signonForm"]')
    await signInButton.click()
    await expect(page).toHaveURL('https://jpetstore.aspectran.com/account/signonForm')
})

test('отображение поля логина -> отображается на странице ', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    await expect(usernameInput).toBeVisible()    
})

test('отображение поля пароля -> отображается на странице ', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const passwordInput = page.locator('[name="password"]')       
    await expect(passwordInput).toBeVisible()
})

test('отображение кнопки входа -> отображается на странице, называется "Login" ', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const loginButton = page.locator('.button').last()
    await expect(loginButton).toBeVisible()   
    await expect(loginButton).toHaveText('Login')   
})

test('отображение ссылки для регистрации -> отображается на странице, текст "Register Now!" ', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const signUpLink = page.locator('[class="panel register"]')
    await expect(signUpLink).toBeVisible()   
    await expect(signUpLink).toContainText('Register Now!')  
})

test('ввести валидный логин и пароль, нажать "Login" -> осуществляется вход в приложение', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    const passwordInput = page.locator('[name="password"]') 
    const loginButton = page.locator('.button').last()
    await usernameInput.click()
    await usernameInput.press('Control+A')
    await usernameInput.press('Backspace')
    await usernameInput.fill('TestID')
    await passwordInput.click()
    await passwordInput.press('Control+A')
    await passwordInput.press('Backspace')
    await passwordInput.fill('654321')
    await loginButton.click()
    const welcomeContent = page.locator('[id="WelcomeContent"]')
    await expect(welcomeContent).toBeVisible()  
    await expect(welcomeContent).toHaveText('Welcome TestFirstName!')    
})

test('ввести невалидный логин и пароль, нажать "Login" -> осуществляется вход в приложение', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    const passwordInput = page.locator('[name="password"]') 
    const loginButton = page.locator('.button').last()
    await usernameInput.click()
    await usernameInput.press('Control+A')
    await usernameInput.press('Backspace')
    await usernameInput.fill('0')
    await passwordInput.click()
    await passwordInput.press('Control+A')
    await passwordInput.press('Backspace')
    await passwordInput.fill('0')
    await loginButton.click()
    const errorMessage = page.locator('[class="panel failed"]')
    await expect(errorMessage).toBeVisible()
    await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
})

test('ввести валидный логин, невалидный пароль, нажать "Login" -> осуществляется вход в приложение', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    const passwordInput = page.locator('[name="password"]') 
    const loginButton = page.locator('.button').last()
    await usernameInput.click()
    await usernameInput.press('Control+A')
    await usernameInput.press('Backspace')
    await usernameInput.fill('TestID')
    await passwordInput.click()
    await passwordInput.press('Control+A')
    await passwordInput.press('Backspace')
    await passwordInput.fill('0')
    await loginButton.click()
    const errorMessage = page.locator('[class="panel failed"]')
    await expect(errorMessage).toBeVisible()
    await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
})

test('ввести невалидный логин, валидный пароль, нажать "Login" -> осуществляется вход в приложение', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    const passwordInput = page.locator('[name="password"]') 
    const loginButton = page.locator('.button').last()
    await usernameInput.click()
    await usernameInput.press('Control+A')
    await usernameInput.press('Backspace')
    await usernameInput.fill('0')
    await passwordInput.click()
    await passwordInput.press('Control+A')
    await passwordInput.press('Backspace')
    await passwordInput.fill('654321')
    await loginButton.click()
    const errorMessage = page.locator('[class="panel failed"]')
    await expect(errorMessage).toBeVisible()
    await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
})

test('не запонять поля, нажать "Login" ->  ошибка, авторизация не прошла ', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    const passwordInput = page.locator('[name="password"]') 
    const loginButton = page.locator('.button').last()
    await usernameInput.click()
    await usernameInput.press('Control+A')
    await usernameInput.press('Backspace')
    await usernameInput.fill('')
    await passwordInput.click()
    await passwordInput.press('Control+A')
    await passwordInput.press('Backspace')
    await passwordInput.fill('')
    await loginButton.click()
    const errorMessage = page.locator('[class="panel failed"]')
    await expect(errorMessage).toBeVisible()
    await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
})

test('оставить пустым только логин, нажать "Login" -> ошибка, авторизация не прошла', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    const passwordInput = page.locator('[name="password"]') 
    const loginButton = page.locator('.button').last()
    await usernameInput.click()
    await usernameInput.press('Control+A')
    await usernameInput.press('Backspace')
    await usernameInput.fill('')
    await passwordInput.click()
    await passwordInput.press('Control+A')
    await passwordInput.press('Backspace')
    await passwordInput.fill('654321')
    await loginButton.click()
    const errorMessage = page.locator('[class="panel failed"]')
    await expect(errorMessage).toBeVisible()
    await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
})

test('оставить пустым только пароль, нажать "Login" -> ошибка, авторизация не прошла', async({page})=>{
    await page.goto('https://jpetstore.aspectran.com/account/signonForm')
    const usernameInput = page.locator('[name="username"]')
    const passwordInput = page.locator('[name="password"]') 
    const loginButton = page.locator('.button').last()
    await usernameInput.click()
    await usernameInput.press('Control+A')
    await usernameInput.press('Backspace')
    await usernameInput.fill('TestID')
    await passwordInput.click()
    await passwordInput.press('Control+A')
    await passwordInput.press('Backspace')
    await passwordInput.fill('')
    await loginButton.click()
    const errorMessage = page.locator('[class="panel failed"]')
    await expect(errorMessage).toBeVisible()
    await expect(errorMessage).toHaveText('Invalid username or password.  Signon failed.')
})